Traceback (most recent call last):
  File "/gpfs/research/fangroup/rk18g/longitudinal/sc_longitudinal_infer/test_best_cluster_sol/real_data/../../../BnpC/run_BnpC.py", line 295, in <module>
    main(args)
  File "/gpfs/research/fangroup/rk18g/longitudinal/sc_longitudinal_infer/test_best_cluster_sol/real_data/../../../BnpC/run_BnpC.py", line 290, in main
    generate_output(args, results, data, data_names)
  File "/gpfs/research/fangroup/rk18g/longitudinal/sc_longitudinal_infer/test_best_cluster_sol/real_data/../../../BnpC/run_BnpC.py", line 238, in generate_output
    io.save_geno_plots(inferred, data_raw, out_dir, names)
  File "/gpfs/research/fangroup/rk18g/longitudinal/BnpC/libs/dpmmIO.py", line 274, in save_geno_plots
    pl.plot_raw_data(
  File "/gpfs/research/fangroup/rk18g/longitudinal/BnpC/libs/plotting.py", line 160, in plot_raw_data
    cm.gs.set_width_ratios([0, 0, 1])
  File "/gpfs/home/rk18g/.conda/envs/pythonenv/lib/python3.9/site-packages/matplotlib/gridspec.py", line 111, in set_width_ratios
    raise ValueError('Expected the given number of width ratios to '
ValueError: Expected the given number of width ratios to match the number of columns of the grid

real	4m55.718s
user	4m51.331s
sys	0m1.472s
